@host=http://localhost:3200

### récupérer 1 User
GET {{host}}/user/3


### update user
PATCH {{host}}/user/1/save
Content-Type: application/json

### ajouter un user
POST {{host}}/signup
Content-Type: application/json

{
        "mail": "val@gmail.com",
        "lastname": "middle",
        "firstname": "Val",
        "pseudo": "Val.du.lundi",
        "password": "tomate"
    }

###
POST {{host}}/login
Content-Type: application/json

{
        "mail": "anthony@gmail.com",
        "lastname": "",
        "firstname": "",
        "pseudo": "",
        "password": "champignon"
    }

###
DELETE {{host}}/user/5
Content-Type: application/json

{
        "mail": "anthony@gmail.com",
        "lastname": "",
        "firstname": "",
        "pseudo": "",
        "password": "champignon"
    }

