@host=http://localhost:3000
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyMiwibWFpbCI6InRydWNAZ21haWwuY29tIiwibGFzdG5hbWUiOiJtaWRkbGUiLCJmaXJzdG5hbWUiOiJ0cnVjIiwicHNldWRvIjoidHJ1Yy5kdS5sdW5kaSJ9LCJpYXQiOjE2NDMxMDA4MTksImV4cCI6MTY0MzEyMjQxOX0.uDFA86df2r22-srIc2TT9X7XBJ4AkHpDGyYZ2CaSyQM

### récupérer 1 User
GET {{host}}/user
Authorization:{{token}}
Content-Type: application/json



### update user
PATCH {{host}}/user
Authorization:{{token}}
Content-Type: application/json

{
  
  "mail": "truc@gmail.com",
  "lastname": "lucy",
  "firstname": "insky",
  "pseudo": "blabla.du.lundi",
  "password":"mozza"
}

### ajouter un user
POST {{host}}/signup
Content-Type: application/json

{
        "mail": "bob@gmail.com",
        "lastname": "dylan",
        "firstname": "robert",
        "pseudo": "blowing",
        "password": "in2wind"
    }

###se connecter
POST {{host}}/login
Content-Type: application/json

{
        "mail": "truc@gmail.com",
        "lastname": "",
        "firstname": "",
        "pseudo": "",
        "password": "peper"
    }

### supprimer son compte
DELETE {{host}}/user
Authorization:{{token}}
Content-Type: application/json



