@host=http://localhost:3200
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjo2MSwiaWF0IjoxNjQzMzU5Njc3LCJleHAiOjE2NDMzODEyNzd9.eHq3hZUfjt-4pDbr4pwnMpuae-lhcP-oFWEuil9oXJ8

###se connecter
POST {{host}}/login
Content-Type: application/json

{
        "mail": "zigg@gmail.com",
        "lastname": "",
        "firstname": "",
        "pseudo": "",
        "password": "ziggy"
    }


###Ajouter un album à la bibli du user
POST {{host}}/dashboard/61/album
# Authorization:{{token}}
Content-Type: application/json

{
        "name": "strut",
        "genre": "rock",
        "artist": "Lenny kravitz",
        "year": "2014",
        "urlImage": "lenny",
        "apiId": 35
        
    }