@host=http://localhost:3200
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjo0OCwiaWF0IjoxNjQzODExMzYxLCJleHAiOjE2NDM4MzI5NjF9.qYmeEHkL7sp8ZLohq68vwrsApZPxj7i4u6vSjy8wCUY

### récupérer 1 User
GET {{host}}/user
Authorization:{{token}}
Content-Type: application/json


### ajouter un user
POST {{host}}/signup
Content-Type: application/json

{
    "mail": "zigg@gmail.com",
    "lastname": "Bowie",
    "firstname": "David",
    "pseudo": "starman",
    "password":"ziggy",
    "password_confirmation":"ziggy"
     }

###se connecter
POST {{host}}/login
Content-Type: application/json

{
        "mail": "zigg@gmail.com",
        "lastname": "",
        "firstname": "",
        "pseudo": "",
        "password": "ziggy"
    }

### update user
PATCH {{host}}/user
Authorization:{{token}}
Content-Type: application/json

{
  "mail": "zigg@gmail.fr",
  "lastname": "Bowie",
  "firstname": "dave",
  "pseudo": "jackB",
  "password": "blabla"
}

### supprimer son compte
DELETE {{host}}/user
Authorization:{{token}}
Content-Type: application/json



