@host=http://localhost:3200
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjo4MywiaWF0IjoxNjQ0MzE0MDU2LCJleHAiOjE2NDQzMTUyNTZ9.2xS6zaMJbwzcuK-hzyIivg7Ow_7oRSxcg-ACAXh8-cs

### récupérer 1 User
GET {{host}}/user
Authorization:{{token}}
Content-Type: application/json


### ajouter un user
POST {{host}}/signup
Content-Type: application/json

{
    "mail": "bossman@mail.fr",
    "lastname": "Bosse",
    "firstname": "Uggo",
    "pseudo": "Alive",
    "password":"bossman",
    "password_confirmation": "bossman"
     }

###se connecter
POST {{host}}/login
Content-Type: application/json

{
        "mail": "bossman@mail.fr",
        "lastname": "",
        "firstname": "",
        "pseudo": "",
        "password": "bossman"
    }

### update user
PATCH {{host}}/user
Authorization:{{token}}
Content-Type: application/json

{
  "mail": "bossman@mail.fr",
    "lastname": "Bosse",
    "firstname": "Uggo",
    "pseudo": "Alive",
    "password":"bossman",
    "password_confirmation": "bossman"
}

### supprimer son compte
DELETE {{host}}/user
Authorization:{{token}}
Content-Type: application/json



