@host=http://localhost:3200
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjo4OCwiaWF0IjoxNjQ0MzE3MjcyLCJleHAiOjE2NDQzMTg0NzJ9.j3d6cCY7LGrcvd777pT6p2i-rMg1FGHTmDmDZyAH-5c
Authorization:{{token}}
Content-Type: application/json


### ajouter un user
POST {{host}}/signup
Content-Type: application/json

{
    "mail": "bossman@mail.fr",
    "lastname": "Bosse",
    "firstname": "Uggo",
    "pseudo": "Alive",
    "password":"bossman",
    "password_confirmation": "bossman"
     }

###se connecter
POST {{host}}/login
Content-Type: application/json

{
        "mail": "bossman@mail.fr",
        "lastname": "",
        "firstname": "",
        "pseudo": "",
        "password": "bossman12$$_"
    }

### update user
PATCH {{host}}/user
Authorization:{{token}}
Content-Type: application/json

{
  "mail": "bossman@mail.fr",
    "lastname": "Bosse",
    "firstname": "Uggo",
    "pseudo": "Alive",
    "password":"boss",
    "password_confirmation": "boss"
}

### supprimer son compte
DELETE {{host}}/user
Authorization:{{token}}
Content-Type: application/json



